---
title: "Traitement du biais de sélection dans les enquêtes multimodes séquentielles"
author: "Odilon Saint-Cry DAKPAKETE, Marius DURAND-BARRIER, Ilyass MESSABEL & TANO
  Anoumou Marc "
date: "2025-02-12"
output:
  pdf_document:
    number_sections: true
    toc: true
  html_document:
    toc: true
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amsfonts}
- \usepackage{amssymb}
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{titling}
- \pretitle{\begin{center}\LARGE\bfseries\vspace{5cm}}
- \posttitle{\par\end{center}\vspace{1cm}}
- \preauthor{\begin{center}\LARGE}
- \postauthor{\par\end{center}\vspace{10cm}}
- \newpage
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("xfun")
# update.packages(ask = FALSE) # Mise à jour des packages R
# install.packages("xfun", dependencies = TRUE)
# utils::install.packages(c("tinytex", "rmarkdown"))
# utils::contrib.url(repos, "source")
```

\newpage
# Introduction

Le processus de réalisation d’une enquête repose sur plusieurs étapes essentielles, telles que la formulation de la problématique, la conception des questionnaires, la mise en œuvre de la collecte des données et leur suivi. Chacune de ces phases peut générer des erreurs en l'absence d'une méthode rigoureuse. L'ensemble de ces erreurs constitue l'erreur totale de l'enquête.

Certaines erreurs proviennent de l'administration du questionnaire, c'est-à-dire des difficultés liées aux différents modes de collecte des données. Ce problème se manifeste particulièrement dans les enquêtes multimodes, qui combinent divers supports (Internet, téléphone, face-à-face, papier) afin d'optimiser le taux de réponse tout en maîtrisant les coûts.

Le développement rapide des technologies numériques a favorisé l'émergence des enquêtes multimodes, transformant ainsi les méthodes de collecte de données. L'utilisation simultanée de plusieurs modes permet de mieux répondre aux besoins d'une population de plus en plus diversifiée, tout en soulevant d'importants défis méthodologiques. Par exemple, le protocole séquentiel, souvent utilisé, propose d'abord un mode de collecte (généralement Internet), suivi d'un mode complémentaire (téléphone ou face-à-face) en cas de non-réponse. Bien que cette stratégie permette de maîtriser les coûts et d'augmenter le taux de réponse, elle expose l'enquête à deux types de biais majeurs :

  - Le biais de sélection survient lorsque la probabilité de participation dépend directement de la variable d'intérêt (Y). Ainsi, le profil des répondants peut varier selon le mode de collecte, ce qui complique l'interprétation des résultats et limite l'efficacité des méthodes classiques de redressement.

  - Le biais de mesure se traduit par des réponses divergentes d'un même individu selon le mode de collecte utilisé. Par exemple, lors d'une enquête téléphonique, un répondant peut être tenté d'ajuster ses réponses pour se conformer aux normes sociales, contrairement à ce qu'il ferait dans un questionnaire auto-administré.

Ce projet se concentre sur le biais de sélection dans le cadre d'une enquête multimode séquentielle combinant Internet et téléphone. Plus précisément, il vise à tester, au moyen de simulations de données, la validité des méthodes classiques de redressement en présence d'un biais de non-réponse non-ignorable. L'objectif est de déterminer jusqu'à quel point ces méthodes restent efficaces et à partir de quel seuil l'influence des variables non observables (U) compromet leur performance.

Pour ce faire, nous allons travailler sur les variables suivantes : 

* X0 une variables auxiliaire connue pour les répondants et non-répondants ; 
* X1 une variables sociodémographique connue uniquement pour les répondants ; 
* Y la variable d’intérêt, connue uniquement pour les répondants : Y est expliquée par X0 et X1, mais aussi U  
* U une variable non mesurée affectant la probabilité de réponse à Internet, au téléphone et Y, calculée pour les répondants et les non-répondants 
* Pi la probabilité de répondre sur Internet 
* Pt la probabilité de répondre au téléphone 

\newpage

# Le concepte théorique 
## La formulation de l'indicateur d'intérêt

Pour commencer, nous faisons l'hypothése dans ce projet que Y est une variable numérique et nous nous intéressons à l'estimation de sa moyenne ($\mu$).
Dans le cas où nous connaissons toutes les valeurs des $Y_{i}$ de la population, cette moyenne serait définit par la formule suivante :

$$\mu = \frac{1}{N}\sum_{i=1}^N Y_{i}$$
Etant donné qu'il s'agit d'une enquête, nous ne connaissons pas toutes les valeurs de $Y_{i}$, nous devons donc estimer cette moyenne. Comme cela a été dit dans le document de travail (CASTELL, SILLARD, 2021), le plan de sondage est définie par le vecteur $S = (s_{1}, s_{2}, ..., s_{N})$ avec $s_{i}$ une variable aléatoire prenons la valeur 1 si l'individu i est sélectionné dans le plan de sondage et 0 sinon.

Ainsi,l'estimateur d'Horvitz-Thompson de la moyenne de Y est donné par la formule suivante :

$$\hat{\mu} = \frac{1}{N}\sum_{i=1}^N \frac{y_{i}}{\pi_{i}}s_{i}$$
Cette estimateur est sans biais, car $\mathbb{E}[s_{i}] = \pi_{i}$ ce qui implique  $\mathbb{E}[\hat{\mu}|y] = \mu$


Dans notre, il s'agit d'une enquête multimode séquentiel (internet, puis téléphone). Il nous faut donc définir deux variables instrumentale qui identifient les réponses par internet et les réponses par téléphone.

Soit $z_{i}$ la variable aléatoire prenant la valeur 1 si l'individu i répond par internet et 0 sinon.

Soit $w_{i}$ la variable aléatoire prenant la valeur 1 si l'individu i répond par téléphone et 0 sinon.


Nous disposons donc de deux vecteurs Z et W qui permettent respectivement d'identifier les réponses par internet et par téléphone. Ces vecteurs sont nos variables instrumentales.

Ainsi l'estimateur de la moyenne de Y peut être donné par la formule suivante :

$$\hat{\mu_{1}} = \frac{1}N\sum_{i=1}^N \frac{y_{i}}{\pi_{i}}s_{i}(z_{i}+w_{i}) = \frac{1}N \left(\sum_{i=1}^N \frac{y_{i}}{\pi_{i}}s_{i}z_{i} + \sum_{i=1}^N \frac{y_{i}}{\pi_{i}}s_{i}w_{i}\right)$$

Cette d'estimateur est biaisé, car d'après le document de travail (CASTELL, SILLARD, 2021),$\mathbb{E}[s_{i}(z_{i}+w_{i})]\ne \pi_{i}$
On pose $r_{i} = (z_{i}+w_{i})$

Pour pouvoir corriger ce biais, nous introduisons $\hat\rho_{1}$ et $\hat\rho_{2}$ qui seront respectivement des modèles de $z_{i}$ et de $w_{i}$ de sorte que $\mathbb{E}[\hat{\mu_{2}}|y] = \mu$, c'est à dire nous allons estimer $\hat\rho_{1}$ et $\hat\rho_{2}$ de sorte que $\hat{\mu_{2}}$ soit sans biais.

$$\hat{\mu_{2}} = \frac{1}N \left(\sum_{i=1}^N \frac{y_{i}}{\pi_{i}\hat\rho_{1}}s_{i}z_{i} + \sum_{i=1}^N \frac{y_{i}}{\pi_{i}\hat\rho_{2}}s_{i}w_{i}\right)$$

## La correction des biais de selection
Dans notre cas, il s'agit de traiter le biais de non-réponse non-ignorable. Pour cela, nous allons utiliser les méthodes de redressement suivantes :
